# Generated by Django 4.1.4 on 2022-12-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
